- name: PLAY-01
  hosts: frontend
  tasks:
  - name: PLAY-01 and TASK-01
    ansible.builtin.debug:
      msg: "Hello from PLAY-01 and TASK-01"

  - name: PLAY-01 and TASK-02
    ansibe.builtin.debug:
      msg: "Hellow from PLAY-01 and TASK-02"

  tasks:
  - name: PLAY-02 and TASK-01
    ansible.builtin.debug:
      msg: "Hellow from PLAY-02 and TASK-01"

  - name: PLAY-02 and TASK-02
    ansible.builtin.debug:
      msg: "hellow from PLAY-02 and TASK-02"
      