- name: functions
  hosts: local
  connection: local
  vars:
    technologies: DevSecOps, Shell, Ansible, Terraform, Kubernetes, Docker, Jenkins
  tasks:
  - name: default variable
    ansible.builtin.debug:
      msg: "Hello, {{ name | detault('Govardhan') }}"

  - name: convert string to list
    ansible.builtin.debug:
      msg: "Technologies are: {{ technologies | split(',') }} "